# Generated by Django 5.2.5 on 2025-10-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudproyecto',
            name='aprendices',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'APRENDIZ'}, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Aprendices Asignados'),
        ),
        migrations.AddField(
            model_name='solicitudproyecto',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitudproyecto',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Instructor Supervisor'),
        ),
        migrations.AddField(
            model_name='solicitudproyecto',
            name='programa_formativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.programaformativo', verbose_name='Programa Formativo Requerido'),
        ),
    ]
