# Generated by Django 5.2.5 on 2025-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaformativo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='programaformativo',
            name='tipo',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('ESPECIALIZACION', 'Especialización Tecnológica'), ('UNIVERSITARIO', 'Universitario')], default=1, max_length=20, verbose_name='Tipo de Programa'),
            preserve_default=False,
        ),
    ]
