# Generated by Django 5.2.6 on 2025-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_solicitudproyecto_aprendices'),
        ('usuario', '0002_programaformativo_descripcion_programaformativo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaprendiz',
            name='proyectos_asignados',
            field=models.ManyToManyField(blank=True, related_name='aprendices_asignados', to='empresas.solicitudproyecto'),
        ),
    ]
