# Generated by Django 5.2.5 on 2025-10-13 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfilaprendiz_proyectos_asignados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilaprendiz',
            name='proyectos_asignados',
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Contacto')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(choices=[('soporte_tecnico', 'Soporte Técnico (Error, Bug)'), ('consulta_general', 'Consulta General sobre el Proyecto'), ('sugerencia', 'Sugerencia o Colaboración'), ('otro', 'Otro Motivo')], max_length=50, verbose_name='Asunto de la Consulta')),
                ('mensaje', models.TextField(verbose_name='Mensaje Detallado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
