# Generated by Django 5.2.5 on 2025-10-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_remove_perfilaprendiz_proyectos_asignados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programaformativo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
