# Generated by Django 5.2.4 on 2025-10-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0005_programaformativo_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilaprendiz",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                    ("PA", "Pasaporte"),
                    ("TI", "Tarjeta de Identidad"),
                    ("DNI", "DNI"),
                ],
                default="CC",
                help_text="Selecciona tu tipo de documento",
                max_length=10,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="perfilinstructor",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                    ("PA", "Pasaporte"),
                    ("TI", "Tarjeta de Identidad"),
                    ("DNI", "DNI"),
                ],
                default="CC",
                help_text="Selecciona tu tipo de documento",
                max_length=10,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
