# Generated by Django 5.2.6 on 2025-10-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_perfilaprendiz_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilaprendiz',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('DNI', 'DNI')], default='CC', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='perfilinstructor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('DNI', 'DNI')], default='CC', max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
