# Generated by Django 5.2.6 on 2025-10-16 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruta', models.FilePathField(match='.*\\.sqlite3$', path='backups/', recursive=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamano', models.FloatField(help_text='Tamaño en MB')),
            ],
        ),
    ]
