# Generated by Django 5.2.6 on 2025-10-06 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_alter_solicitudproyecto_aprendices_and_more'),
        ('usuario', '0002_programaformativo_descripcion_programaformativo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuario.perfilaprendiz')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empresas.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Postulación de Aprendiz',
                'verbose_name_plural': 'Postulaciones de Aprendices',
                'unique_together': {('aprendiz', 'proyecto')},
            },
        ),
    ]
