# Generated by Django 5.2.6 on 2025-10-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postulacion',
        ),
    ]
