# Generated by Django 5.2.5 on 2025-10-14 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0003_initial"),
        ("usuario", "0004_remove_perfilaprendiz_proyectos_asignados_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AprendizProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ficha",
                    models.CharField(
                        default="N/A", max_length=10, verbose_name="Número de Ficha"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Número de Celular",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="aprendices/fotos_perfil/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Aprendiz",
                "verbose_name_plural": "Perfiles de Aprendices",
            },
        ),
        migrations.DeleteModel(
            name="Postulacion",
        ),
    ]
