# Generated by Django 5.2.5 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0004_aprendizprofile_delete_postulacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprendizprofile",
            name="celular",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número de Celular"
            ),
        ),
    ]
