# Generated by Django 5.2.4 on 2025-10-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0005_alter_aprendizprofile_celular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aprendizprofile",
            name="ficha",
        ),
        migrations.AddField(
            model_name="aprendizprofile",
            name="documento",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Número de Documento",
            ),
        ),
        migrations.AddField(
            model_name="aprendizprofile",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                    ("PA", "Pasaporte"),
                    ("TI", "Tarjeta de Identidad"),
                    ("DNI", "DNI"),
                ],
                default="CC",
                max_length=10,
                null=True,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
