# Generated by Django 5.2.5 on 2025-10-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('area', models.CharField(max_length=100, verbose_name='Área de Aplicación')),
                ('duracion_semanas', models.PositiveIntegerField(verbose_name='Duración Estimada (Semanas)')),
                ('estado', models.CharField(choices=[('EN_DESARROLLO', 'En desarrollo'), ('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente/Revisión'), ('APROBADO', 'Aprobado para Asignación'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proyecto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Solicitud de Proyecto',
                'verbose_name_plural': 'Solicitudes de Proyectos',
            },
        ),
    ]
