# Generated by Django 5.2.5 on 2025-10-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='aprendices',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', to='usuario.perfilaprendiz', verbose_name='Aprendices Asignados'),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='usuario.perfilempresa', verbose_name='Empresa Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_supervisados', to='usuario.perfilinstructor', verbose_name='Instructor Supervisor'),
        ),
    ]
