# Generated by Django 5.2.6 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_solicitudproyecto_aprendices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='area',
            field=models.CharField(choices=[('DES', 'Desarrollo de Software'), ('IND', 'Ingeniería Industrial'), ('ADM', 'Administración y Gestión Empresarial'), ('ELE', 'Electricidad y Electrónica'), ('MEC', 'Mecánica y Mantenimiento'), ('CON', 'Construcción e Infraestructura'), ('AMB', 'Medio Ambiente y Energías Renovables'), ('SAL', 'Salud y Bienestar'), ('TUR', 'Turismo y Hotelería'), ('ART', 'Arte, Diseño y Multimedia')], max_length=3, verbose_name='Área de Aplicación'),
        ),
    ]
