# Generated by Django 5.2.6 on 2025-10-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_solicitudproyecto_area'),
        ('usuario', '0002_programaformativo_descripcion_programaformativo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Postulación')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_proyecto', to='usuario.perfilaprendiz', verbose_name='Aprendiz')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_aprendices', to='empresas.solicitudproyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Postulación de Aprendiz',
                'verbose_name_plural': 'Postulaciones de Aprendices',
                'unique_together': {('aprendiz', 'proyecto')},
            },
        ),
    ]
