# Generated by Django 5.2.6 on 2025-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_postulacion'),
        ('usuario', '0002_programaformativo_descripcion_programaformativo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='aprendices',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_asignadas', to='usuario.perfilaprendiz', verbose_name='Aprendices Asignados'),
        ),
    ]
