# Generated by Django 5.2.6 on 2025-10-13 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_solicitudproyecto_aprendices'),
        ('usuario', '0003_perfilaprendiz_proyectos_asignados'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Postulación')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_instructor', to='usuario.perfilinstructor', verbose_name='Instructor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_instructores', to='empresas.solicitudproyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Postulación de Instructor',
                'verbose_name_plural': 'Postulaciones de Instructores',
                'unique_together': {('instructor', 'proyecto')},
            },
        ),
    ]
