# Generated by Django 5.2.5 on 2025-10-13 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_postulacioninstructor'),
        ('usuario', '0004_remove_perfilaprendiz_proyectos_asignados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Sector Productivo')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='postulacioninstructor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postulacioninstructor',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='postulacioninstructor',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='aprendices',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', to='usuario.perfilaprendiz', verbose_name='Aprendices Asignados'),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área de Aplicación'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT / Identificación Fiscal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo Corporativo')),
                ('tamano', models.CharField(blank=True, choices=[('Micro', '1 a 10 empleados'), ('Pequeña', '11 a 50 empleados'), ('Mediana', '51 a 250 empleados'), ('Grande', 'Más de 250 empleados')], max_length=10, null=True, verbose_name='Tamaño de la Empresa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_corporativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Contacto')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.sector', verbose_name='Sector Productivo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.DeleteModel(
            name='Postulacion',
        ),
        migrations.DeleteModel(
            name='PostulacionInstructor',
        ),
    ]
