# Generated by Django 5.2.5 on 2025-10-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "empresas",
            "0008_sector_alter_postulacioninstructor_unique_together_and_more",
        ),
        ("usuario", "0004_remove_perfilaprendiz_proyectos_asignados_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuario.sectorproductivo",
                verbose_name="Sector Productivo",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudproyecto",
            name="aprendices",
            field=models.ManyToManyField(
                blank=True,
                related_name="solicitudes_asignadas",
                to="usuario.perfilaprendiz",
                verbose_name="Aprendices Asignados",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudproyecto",
            name="area",
            field=models.CharField(
                choices=[
                    ("DES", "Desarrollo de Software"),
                    ("IND", "Ingeniería Industrial"),
                    ("ADM", "Administración y Gestión Empresarial"),
                    ("ELE", "Electricidad y Electrónica"),
                    ("MEC", "Mecánica y Mantenimiento"),
                    ("CON", "Construcción e Infraestructura"),
                    ("AMB", "Medio Ambiente y Energías Renovables"),
                    ("SAL", "Salud y Bienestar"),
                    ("TUR", "Turismo y Hotelería"),
                    ("ART", "Arte, Diseño y Multimedia"),
                ],
                max_length=3,
                verbose_name="Área de Aplicación",
            ),
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Postulación",
                    ),
                ),
                (
                    "fecha_postulacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Postulación"
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones_proyecto",
                        to="usuario.perfilaprendiz",
                        verbose_name="Aprendiz",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones_aprendices",
                        to="empresas.solicitudproyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postulación de Aprendiz",
                "verbose_name_plural": "Postulaciones de Aprendices",
                "unique_together": {("aprendiz", "proyecto")},
            },
        ),
        migrations.CreateModel(
            name="PostulacionInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Postulación",
                    ),
                ),
                (
                    "fecha_postulacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Postulación"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones_instructor",
                        to="usuario.perfilinstructor",
                        verbose_name="Instructor",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones_instructores",
                        to="empresas.solicitudproyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postulación de Instructor",
                "verbose_name_plural": "Postulaciones de Instructores",
                "unique_together": {("instructor", "proyecto")},
            },
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
    ]
