# Generated by Django 5.2.4 on 2025-10-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_alter_empresa_sector_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitudproyecto",
            options={
                "ordering": ["-creado_en"],
                "verbose_name": "Solicitud de Proyecto",
                "verbose_name_plural": "Solicitudes de Proyectos",
            },
        ),
        migrations.AddField(
            model_name="solicitudproyecto",
            name="motivo_aprobacion",
            field=models.TextField(
                blank=True,
                help_text="Motivo por el que se aprobó el proyecto",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitudproyecto",
            name="motivo_rechazo",
            field=models.TextField(
                blank=True,
                help_text="Motivo por el que se rechazó el proyecto",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudproyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente/Revisión"),
                    ("EN_DESARROLLO", "En desarrollo"),
                    ("COMPLETADO", "Completado"),
                    ("APROBADO", "Aprobado para Asignación"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado del Proyecto",
            ),
        ),
    ]
