# Generated by Django 5.2.4 on 2025-10-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0010_alter_solicitudproyecto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudproyecto",
            name="fecha_decision",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
