# Generated by Django 5.2.6 on 2025-10-08 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_alter_solicitudproyecto_aprendices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'rol': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_instructor', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empresas.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Asignación de Instructor',
                'verbose_name_plural': 'Asignaciones de Instructores',
                'unique_together': {('instructor', 'proyecto')},
            },
        ),
    ]
