# Generated by Django 5.2.5 on 2025-10-13 19:33

import django.db.models.deletion
import instructores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=50, unique=True, verbose_name='No. de Identificación (Cédula/DNI)')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía (Máx. 500 caracteres)')),
                ('nivel_certificacion', models.CharField(choices=[('Basico', 'Certificación Nivel Básico'), ('Intermedio', 'Certificación Nivel Intermedio'), ('Avanzado', 'Certificación Nivel Avanzado'), ('Experto', 'Instructor Experto/Senior')], default='Basico', max_length=50, verbose_name='Nivel de Certificación')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=instructores.models.instructor_profile_path, verbose_name='Foto de Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_instructor_yl', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Perfil de Instructor',
                'verbose_name_plural': 'Perfiles de Instructores',
            },
        ),
    ]
