# Generated by Django 5.2.5 on 2025-10-14 02:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0002_perfilinstructor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PerfilInstructor",
            new_name="InstructorProfile",
        ),
    ]
