# Generated by Django 5.2.5 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0003_rename_perfilinstructor_instructorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorprofile",
            name="numero_identificacion",
            field=models.CharField(
                max_length=10,
                unique=True,
                verbose_name="No. de Identificación (Cédula/DNI)",
            ),
        ),
    ]
