# Generated by Django 5.2.4 on 2025-10-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0004_alter_instructorprofile_numero_identificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofile",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("TI", "Tarjeta de Identidad"),
                    ("CE", "Cédula de Extranjería"),
                    ("PP", "Pasaporte"),
                    ("OTRO", "Otro Documento"),
                ],
                default="CC",
                max_length=5,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
