# Generated by Django 5.2.4 on 2025-10-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0005_instructorprofile_tipo_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorprofile",
            name="numero_identificacion",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="No. de Identificación (Cédula/DNI)",
            ),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("TI", "Tarjeta de Identidad"),
                    ("CE", "Cédula de Extranjería"),
                    ("PP", "Pasaporte"),
                    ("OTRO", "Otro Documento"),
                ],
                default="CC",
                max_length=5,
                null=True,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
